### ISSUE TITLE
Which files to use with Request

### ISSUE THREAD

**Issue by jbeckton** [coolaj86/nodejs-self-signed-certificate-example#4]
Can you help me figure out which of the generated files to use with the options object for Request?
https://www.npmjs.com/package/request

https://www.npmjs.com/package/request#tlsssl-protocol

**Comment by coolaj86** [comment]
https://github.com/coolaj86/nodejs-self-signed-certificate-example/blob/master/request-with-request.js

**Comment by jbeckton** [comment]
Thank you for your help, and I noticed you updated your project example which made things more clear for me as far as which files to use..

I do have one final question for you that is more general SSL. My node app is calling web services via https so I am trying to provide the client certs but I keeping getting  the error "unable to verify the first certificate" returned from the service endpoint.

When I generate my certs with your tool I am using "localhost" as the domain since I am working in my local machine. Should I be using my machines external ip or host name for the cert?

Thanks.

**Comment by coolaj86** [comment]
I don't think `localhost` is a valid FQDN, but you can use `localhost.daplie.com` which points to 127.0.0.1 also. The root cert is hard-coded as `example.com`, which should work fine.

Run the example in the README exactly as is (I did that yesterday before I pushed) and see if that works for you.

You might also try adjusting the example to use `certs/server/cert.pem` instead of `certs/server/fullchain.pem` for `cert`.

There are some peculiarities using self-created root authorities. Normally you include the certificate that signed your certificate in your `fullchain.pem`, but in this case since that is also the root certificate it may cause some clients to fail verifying the certificates in the chain before it loads the root.

Also, here's a guide that is probably too much detail for what you're trying to do, but includes the missing steps to create an intermediate cert (at which point everything is EXACTLY the same as if you had purchased your cert through Verisign, minus their name being on the root), which I wasn't familiar with at the time I created this example:
https://jamielinux.com/docs/openssl-certificate-authority/

**Comment by jbeckton** [comment]
Thanks again..

After talking with another developer at the company I am working for I
found out that they have certs that we are supposed to use at the OS level.
The stuff I am building is all internal so they have a CA for everyone to
configure into the machines used to host the apps. This should fix my
issues.


Best Regards,
Jesse

**Comment by coolaj86** [comment]
Ah, yes, and that's the scenario the other guide I linked to is meant for too.
